name: fist workflow

on:
  push:
    branches:
      - main

jobs:
  exjob:
    runs-on: ubuntu-latest

    steps:
      - name: xxxxx
        run: echo xxx

      - name: checkout repo
        uses: actions/checkout@v6-beta

      - name: repos
        run: ls -la

